### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

##### import numpy as np


###### 1. Write a NumPy program to find the missing data in a given array.

In [2]:
import numpy as np

In [4]:
### code here
x=np.array([[3,2,np.nan,1],[10,12,10,9],[5,np.nan,1,np.nan]])
print("Original array:\n",x)
print("missing data of said array :\n",np.isnan(x))

Original array:
 [[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]
missing data of said array :
 [[False False  True False]
 [False False False False]
 [False  True False  True]]


In [ ]:
## sample output

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


##### 2. Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [2]:
### code here 
A=np.arange(1,21).reshape(4,5)
A1=np.arange(1,21).reshape(4,5)
print(np.array_equal(A,A1))
print(A==A1)

True
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [4]:
B=np.arange(0,20).reshape(5,4)
B1=np.arange(1,21).reshape(5,4)
np.array_equal(B,B1)

False

###### 3. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [27]:
## code here
x=np.arange(0,16).reshape(4,4)
print(x)
print("\n",x[3:,::])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 [[12 13 14 15]]


In [ ]:
## sample output

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


###### 4. Write a NumPy program to convert a list and tuple into arrays.

In [16]:
#### code here
l=[1,2,3,4]
print(np.array(l))
print(np.array([l]))

[1 2 3 4]
[[1 2 3 4]]


In [20]:
tpl=(1,2,3,4,5)
print(np.array(tpl))
print(np.array([tpl]))

[1 2 3 4 5]
[[1 2 3 4 5]]


###### 5. Write a NumPy program to find common values between two arrays.

In [13]:
P=np.random.random(4)
P

array([0.47005642, 0.83266266, 0.84004255, 0.75887879])

In [14]:
Q=np.random.random(4)
Q

array([0.74267422, 0.29753399, 0.83209556, 0.88875066])

In [15]:
np.intersect1d(P,Q)

array([], dtype=float64)

In [16]:
### code here
p=np.arange(1,10).reshape(3,3)
p

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
q=np.arange(4,13).reshape(3,3)
q

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
np.intersect1d(p,q)

array([4, 5, 6, 7, 8, 9])

In [66]:
s=np.logical_and(p,q)
s[np.any(s)]

array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])

###### 6. Write a NumPy program to create a new shape to an array without changing its data.

In [26]:
### code here
n=np.arange(1,7)
print("Reshape 3x2 :\n",n.reshape(3,2))
print("Reshape 2x3 :\n",n.reshape(2,3))

Reshape 3x2 :
 [[1 2]
 [3 4]
 [5 6]]
Reshape 2x3 :
 [[1 2 3]
 [4 5 6]]


In [ ]:
### sample output

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]


###### 7. Write a NumPy program to count the frequency of unique values in numpy array.

In [42]:
### code here
X=np.array([10,10,20,10,20,20,30,30,20,50,40,40])
print("Original array :\n",X)
G=np.unique(X,return_counts=True)
print("frequency of unique values of said array :\n",G)

Original array :
 [10 10 20 10 20 20 30 30 20 50 40 40]
frequency of unique values of said array :
 (array([10, 20, 30, 40, 50]), array([3, 4, 2, 2, 1], dtype=int64))


In [43]:
np.unique(X,return_counts=True)

(array([10, 20, 30, 40, 50]), array([3, 4, 2, 2, 1], dtype=int64))

In [ ]:
## sample output

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


###### 8. Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

In [47]:
### code here
a1=np.array([[0,0,0],[1,2,3],[4,5,6]])

In [48]:
a2=np.array([10,11,12])

In [52]:
print("Array-1: \n",a1)
print("Array-2:\n",a2)
print()
print("New Array :\n",a1+a2)


Array-1: 
 [[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2:
 [10 11 12]

New Array :
 [[10 11 12]
 [11 13 15]
 [14 16 18]]


In [ ]:
## sample output

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


###### 9. Write a NumPy program to extract all the elements of the second row from a given (4x4) array.

In [ ]:
### code here

In [53]:
import numpy as np
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Second row")
print(arra_data[1,:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


###### 10. Write a NumPy program to extract third and fourth elements of the first and second rows from a given (4x4) array.

In [55]:
## code here
z1=np.arange(0,16).reshape(4,4)
z2=z1[:2,2:]
print("Original array :\n",z1)
print("\nExtracted data: third and fourth element of first and second rows \n",z2)

Original array :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: third and fourth element of first and second rows 
 [[2 3]
 [6 7]]


In [ ]:
## sample output


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows 
[[2 3]
 [6 7]]


###### 11. Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [7]:
### code here
a=np.datetime64("today")
print("todays date :",a)
yes=a-np.timedelta64(1,"D")
print("yestarday was :",yes)
tom=a+np.timedelta64(1,"D")
print("tomorrow is :",tom)

todays date : 2022-11-17
yestarday was : 2022-11-16
tomorrow is : 2022-11-18


###### 12. Write a NumPy program to find the first Monday in May 2017.

In [23]:
## code here
n=np.arange("2017-05-01","2017-05-31",dtype="datetime64[D]")

for i in n:
    print("first monday in May 2017 :\n",n[0])
    break

first monday in May 2017 :
 2017-05-01


In [15]:
## sample output
c=n[0]
print("first monday in 2017 :\n",c)

first monday in 2017 :
 2017-05-01
