### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

In [1]:
import numpy as np

#####1.  Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [6]:
### code here
x=np.zeros(10)
y=np.ones(10)
z=np.array([5,5,5,5,5,5,5,5,5,5],dtype=float)

In [7]:
print("an array of 10 zeros : \n",x)
print("an array of 10 ones :\n",y)
print("an array of 10 fives :\n",z)


an array of 10 zeros : 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
an array of 10 ones :
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
an array of 10 fives :
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [3]:
np.full((1,10),5)

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [ ]:
## sample output

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#####2.  Write a NumPy program to create an array of the integers from 30 to 70.

In [11]:
### code here
a=np.arange(30,71)
print("array of integers from 30 to 70 \n",a)

array of integers from 30 to 70 
 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [ ]:
### sample output

Array of the integers from 30 to70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


######3. Write a NumPy program to create an array of all the even integers from 10 to 50.

In [14]:
### code here
a1=np.arange(10,50)
print("array of all the even integers from 10 to 50\n",a1[a1%2==0])

array of all the even integers from 10 to 50
 [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [ ]:
## sample output


Array of all the even integers from 10 to 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


######4. Write a NumPy program to create a 3x3 identity matrix.

In [16]:
### code here
e=np.eye(3)
print("3x3 matrix :\n",e)

3x3 matrix :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
## sample output

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### 5. Write a NumPy program to generate a random number between 0 and 1

In [19]:
### code here
r=np.random.random(1)
print("Random number between 0 and 1 :\n",r)

Random number between 0 and 1 :
 [0.52861179]


In [ ]:
## sample output

Random number between 0 and 1:
[0.40400053]


###### 6. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [26]:
l=np.linspace(0,1,15)
l

array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
       0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714,
       0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.        ])

In [21]:
## code here
r1=np.random.random(15)
print("15 random numbers from a standard normal distribution :\n",r1)

15 random numbers from a standard normal distribution :
 [0.66295709 0.23738836 0.13677889 0.89171832 0.9425661  0.11014925
 0.55794892 0.6893487  0.28273865 0.56770855 0.6515102  0.4984509
 0.62416957 0.94335707 0.75516419]


In [ ]:
## sample output

15 random numbers from a standard normal distribution:
[ 0.68439314  1.50916987 -0.75364839  0.1038106   0.07789927 -0.15349755
  1.78151615  0.49989426  0.18791322 -1.51931266 -0.55512066  2.02808972
  0.37648568  0.57999878 -0.31095957]


###### 7. Write a NumPy program to create a 3X4 array using and iterate over it.

In [4]:
## code here
b=np.arange(10,22).reshape(3,4) 
print("original array :\n",b)
b.flatten()


original array :
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [17]:
l=[]
for r in b:
    for c in r:
        l.append(c)
print(l)
        

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]


###### 8. Write a NumPy program to multiply the values ​​of two given vectors.

In [30]:
## code here
x=np.array([1,8,3,5])
y=np.array([10,1,4,10])
print(np.multiply(x,y))

[10  8 12 50]


In [34]:
print("vector-1\n",x)
print("vector-2\n",y)
print("mutiplication of two said vectors :\n",x*y)

vector-1
 [1 8 3 5]
vector-2
 [10  1  4 10]
mutiplication of two said vectors :
 [10  8 12 50]


In [ ]:
## sample output

Vector-1
[1 8 3 5]
Vector-2
[10  1  4 10]
Multiply the values of two said vectors:
[10  8 12 50]


###### 9. Write a NumPy program to reverse an array (first element becomes last).

In [38]:
### code here
A=np.arange(12,38)
print("original array:\n",A)
print("Reverse array:\n",A[::-1])

original array:
 [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
 [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [1]:
## sample output

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


##### 10. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [40]:
## code here
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [ ]:
## sample output

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


###### 11. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

In [44]:
## code here
B=np.arange(0,4).reshape(2,2)
print(B)
print("Sum of all elements :\n",np.sum(B))
print("sum of each column :\n",np.sum(B,axis=0))
print("sum of each row :\n",np.sum(B,axis=1))

[[0 1]
 [2 3]]
Sum of all elements :
 6
sum of each column :
 [2 4]
sum of each row :
 [1 5]


In [ ]:
## sample output

Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


###### 12. Write a NumPy program to compute the inner product of two given vectors.

In [52]:
## code here 
g=np.array([4,5])
h=np.array([7,10])
print("original vectors :",g,h,sep="\n")
print("inner product of said vectors :\n",sum(g*h))

original vectors :
[4 5]
[ 7 10]
inner product of said vectors :
 78


In [ ]:
## sample output

Original vectors:
[4 5]
[ 7 10]
Inner product of said vectors:
78
